services:
  Expensify.api:
    image: ${DOCKER_REGISTRY-}Expensifyapi
    container_name: Expensify.Api
    build:
      context: .
      dockerfile: src/API/Expensify.Api/Dockerfile
    depends_on:
      Expensify.database:
        condition: service_healthy
      Expensify.redis:
        condition: service_healthy
      Expensify.seq:
        condition: service_healthy
    environment:
       ASPNETCORE_ENVIRONMENT: Development
       ASPNETCORE_HTTP_PORTS: "8080"
    ports:
      - 5000:8080

  Expensify.database:
    image: postgres:17
    container_name: Expensify.Database
    environment:
      - POSTGRES_DB=Expensify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  Expensify.seq:
    image: datalust/seq:latest
    container_name: Expensify.Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true # local dev only
    ports:
      - 5341:5341
      - 8081:80
    healthcheck:
      test: ["CMD-SHELL", "curl --fail --silent http://localhost:80/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s

  Expensify.redis:
    image: redis:latest
    container_name: Expensify.Redis
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  Expensify.jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: Expensify.Jaeger
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686
